### ISSUE TITLE
extract app/util from generator-trails and generator-trailpack

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/generator-util#1]
https://github.com/trailsjs/generator-trailpack/blob/master/src/app/util.js#L12-L80

**Comment by jaumard** [comment]
We can extract all API/Controller/Service/Model/Policy commands too cause they are the same for both generators.

**Comment by jaumard** [comment]
You can assign me for this, I'll work on this when I can :)

**Comment by jaumard** [comment]
Sounds good @tjwebb  https://github.com/trailsjs/generator-util/pull/2 ? If yes travisCI need to be configured. And if you give me right to the repo I can deploy it and update PR for trails and trailpack generators
